### ISSUE TITLE
Vue with react-native

### ISSUE THREAD

**Issue by joshua1** [GeekyAnts/vue-native-website#1]
Hi,
I just happened on this new repo while browsing the native base repos for starter template (wanted something without typescript and mobx to use with vue-react, so i could write my web and mobile apps with vue). Is this an indication of something in the offing for vue with respect to nativebase ?

**Comment by sanketsahusoft** [comment]
@joshua1 It has no relation with NativeBase at the moment.

We are trying to write a map so that anybody can use Vue to write Native Mobile Apps. So, it's a wrapper around React Native APIs so that people can write Native Apps in Vue style using Vuex and other plugins.

**Comment by joshua1** [comment]
@sanketsahusoft really nice one. I will be watching this closely. been looking for something like this for a while

**Comment by sanketsahusoft** [comment]
@joshua1 We made some good progress! You can start using this project in less than a month. Very excited about this promising project!

Vue is amazing!

**Comment by joshua1** [comment]
@sanketsahusoft will it be possible to use react native components (like the native base ones) with this vue set up

**Comment by sanketsahusoft** [comment]
Yes, it will be possible! :-)
