### ISSUE TITLE
WebView not working

### ISSUE THREAD

**Issue by anson-GH** [GeekyAnts/vue-native-website#17]
After implement the WebView is nothing display.
<template>
    <web-view
        :source="{uri: 'https://github.com/facebook/react-native'}"
        :style="{marginTop: 20}"
    />
</template>

**Comment by neeraj-singh47** [comment]
@anson-GH You can try giving width to the style

**Comment by anson-GH** [comment]
Thanks. It's work.

```
<template>
  <web-view
          :source="{uri: 'https://vue-native.io/docs/basic-components.html#Image'}"
          :style="{width: 150, height: 150}"
    />
</template>
```
It can't work. It shouldn't put outside of view container
<template>
    <view style = {style.container}>
      <web-view
          :source="{uri: 'https://vue-native.io/docs/basic-components.html#Image'}"
          :style="{width: 150, height: 150}"
    />
    </view>
</template>
