### ISSUE TITLE
Switch not working

### ISSUE THREAD

**Issue by anson-GH** [GeekyAnts/vue-native-website#18]
this code not working 
```

<template>
    <view style = {styles.container}>
        <switch
            :on-value-change = "handleChange"
            :value = "value"/>
    </view>
</template>

```

> <script>
>     export default {
>         data: function() {
>             return {
>                 value: false
>             }
>         },
>         methods: {
>             handleChange: () => {
>                 this.value = !this.value
>             }
>         }
>     }
> </script>

**Comment by neeraj-singh47** [comment]
@anson-GH The issue has been resolved. You can refer https://github.com/GeekyAnts/vue-native-core/issues/18.
