### ISSUE TITLE
Expo-cli Stucked during installation

### ISSUE THREAD

**Issue by Muhammad-Yasser1** [GeekyAnts/vue-native-website#35]
when I was going to install vue native app and after wrote vue-native init APP-NAME, I was told to install expo-cli then I write "Y" but it was really slow then stopped so I install expo-cli first then install vue app and it worked,

so the issue is expo-cli installation in vue-native installation not working for me,

thanks

**Comment by neeraj-singh47** [comment]
You interrupted the expo-cli installation. Hence it didn't work
