### ISSUE TITLE
Using BootstrapVue or Custom CSS

### ISSUE THREAD

**Issue by phavor** [GeekyAnts/vue-native-website#37]
I would like to use `bootstrap-vue` in my new project, this is my first time of trying `vue-native`. I can't seem to tell which is the `entry` file or `root` file from where I could do something like this as instructed on `bootstrap-vue`'s docs page:

```
import Vue from "vue";
import BootstrapVue from "bootstrap-vue";

Vue.use(BootstrapVue);

import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";
```

## Other Options

I've also tried importing a custom stylesheet, but this wouldn't work. It throws and `unable to resolve` path to the imported file.

Please how may I use bootstrap with a `vue-native` project?

Thanks

**Comment by neeraj-singh47** [comment]
@phavor bootstrap-vue will not work. You can try out other libraries such as https://react-native-training.github.io/react-native-elements/ or Native Base
